### ISSUE TITLE
Full CAD

### ISSUE THREAD

**Issue by W141-ID** [maximilian-foerg/AM8-plus-Switchwire#2]
Do you mind sharing with us the complete model and all its versions as step or even better f3d file?

**Comment by maximilian-foerg** [comment]
I included the step file in every commit, so you can already access every version of the step file via the repositories history. Full f3d file will come soon

**Comment by W141-ID** [comment]
Full f3d would be awsome! Working on an enclosure and I think the afterburner mod is messing.

**Comment by maximilian-foerg** [comment]
Files are up
