### ISSUE TITLE
Brass Inserts

### ISSUE THREAD

**Issue by MistrPC** [maximilian-foerg/AM8-plus-Switchwire#3]
I see from your supplied pictures, there are some parts that require brass inserts, do you have a list of which parts need the inserts?   Great Build by the way!!

**Comment by Adonay944** [comment]
I suggest you open the STEP File in your favorite cad software or viewer that way you can study the whole construction in detail.

**Comment by maximilian-foerg** [comment]
> I see from your supplied pictures, there are some parts that require brass inserts, do you have a list of which parts need the inserts? Great Build by the way!!

Thank you! I'd actually also recommend you to study the STEP or F3D file with a CAD software as proposed above. May I ask for what purpose such a list would be needed?
